import type { Project } from '@/types/project'

// Jeu de démonstration calibré sur le prototype de référence (inskip-bgl-dashboard.html).
// Utilisé automatiquement tant que NOTION_API_KEY est absente. Remplacé par les
// données Notion réelles dès que la clé est configurée.

const COACH = 'Matthieu Chéreau'
const UPDATED = '2026-06-05'

export const MOCK_PROJECTS: Project[] = [
  {
    notionPageId: 'mock-uc7',
    id: 'UC7',
    name: 'RM Briefing',
    status: 'PROTOTYPE',
    nextSession: '12/06/2026 — Point coaching mensuel',
    confidence: 'high',
    avancement: 55,
    vp: 'Synthèse automatique de la relation client à destination des RM avant chaque rendez-vous, à partir des historiques CRM et des interactions récentes.',
    conformite: {
      dpo: 'Validé',
      risk: 'Faible',
      perso: true,
      notes: [
        'Données CRM internes BGL uniquement',
        'Hébergement sur infrastructure BGL',
        'DPO validé sans restriction ni condition',
        'Pas de données clients externes impliquées',
      ],
    },
    team: [
      { name: 'Victor Dilion', role: 'Porteur principal', org: 'BGL BNP' },
      { name: 'Pierre-Etienne Staes', role: 'Développement', org: 'BGL BNP' },
      { name: 'Sylvain Sarda', role: 'Référent métier', org: 'BGL BNP' },
    ],
    stakeholders: [
      { name: 'Sponsor CoDir', role: 'Sponsor', org: 'Direction Commerciale' },
      { name: 'Matthieu Chéreau', role: 'Coach', org: 'INSKIP' },
    ],
    specs: 3,
    gouv: 3,
    budget: 3,
    tests: 2,
    conformiteScore: 3,
    objectives: [
      { cat: 'PROTOTYPE SYNTHÈSE', desc: 'Finaliser le prototype de synthèse client — 3 formats validés avec les RM', pct: 80 },
      { cat: 'INTÉGRATION CRM LIVE', desc: 'Connecter le modèle aux données CRM live BGL (historique 18 mois)', pct: 45 },
      { cat: 'PILOTE TERRAIN', desc: 'Lancer un pilote sur 5 RM volontaires et mesurer le NPS après 2 semaines', pct: 20 },
    ],
    achievements: [
      'Prototype fonctionnel validé en session Module 3',
      'Budget 2026 engagé — enveloppe confirmée par la direction',
      'DPO validé sans restriction',
      'Sponsor CoDir identifié et engagé',
    ],
    utilisateurs: [
      'Relationship Managers — 40 à 60 utilisateurs cibles',
      'Direction Commerciale — commanditaire et évaluateur',
      'Équipe Data BGL — intégration et maintenance',
    ],
    warnings: ['Plan de déploiement pilote non encore lancé', 'Volumétrie données CRM à calibrer pour la performance'],
    nextSteps: [
      'Lancer le pilote sur 5 RM volontaires',
      "Mesurer le NPS après 2 semaines d'utilisation",
      'Préparer le plan de déploiement pour les 40 RM restants',
    ],
    notesMeta:
      'Projet le plus avancé de la cohort. Sponsor CoDir engagé. Budget 2026 confirmé. DPO validé. Seul blocage : lancement effectif du pilote terrain.',
    module: 'Module 3',
    typeIA: 'IA générative (LLM / RAG)',
    prioriteBudget: 'Budget 2026 engagé',
    coach: COACH,
    lastUpdated: UPDATED,
    validated: false,
  },
  {
    notionPageId: 'mock-uc1',
    id: 'UC1',
    name: 'Aide aux SAR',
    status: 'PROTOTYPE',
    nextSession: '12/06/2026 — Point coaching mensuel',
    confidence: 'high',
    avancement: 45,
    vp: 'Assister les analystes Compliance dans la détection et la rédaction des déclarations de soupçon, en réduisant le temps de traitement par dossier.',
    conformite: {
      dpo: 'Validé',
      risk: 'Moyen',
      perso: true,
      notes: [
        'Données transactionnelles sensibles (AML/CFT)',
        'DPO validé — périmètre clairement défini',
        'Accès restreint aux analystes habilités',
        "Piste d'audit obligatoire sur chaque décision IA",
      ],
    },
    team: [
      { name: 'Porteur UC1', role: 'Analyste Compliance', org: 'BGL BNP' },
      { name: 'Porteur 2 UC1', role: 'Développement', org: 'BGL BNP' },
      { name: 'Porteur 3 UC1', role: 'Référent métier', org: 'BGL BNP' },
    ],
    stakeholders: [
      { name: 'Responsable Conformité', role: 'Sponsor', org: 'BGL Compliance' },
      { name: 'Matthieu Chéreau', role: 'Coach', org: 'INSKIP' },
    ],
    specs: 3,
    gouv: 2,
    budget: 3,
    tests: 2,
    conformiteScore: 3,
    objectives: [
      { cat: 'DÉTECTION ALERTES', desc: 'Prototype de détection SAR avec seuils configurables', pct: 70 },
      { cat: 'INTÉGRATION WORKFLOW', desc: 'Intégrer dans le workflow Compliance existant', pct: 35 },
      { cat: 'TESTS ANALYSTES', desc: '3 sessions de test avec analystes Compliance', pct: 15 },
    ],
    achievements: [
      'Prototype de détection opérationnel',
      'Budget 2026 confirmé par la direction Compliance',
      'DPO validé avec périmètre défini',
    ],
    utilisateurs: [
      'Analystes Compliance — 8 utilisateurs directs',
      'Responsable Conformité — évaluateur final',
      'Régulateur CSSF — destinataire indirect',
    ],
    warnings: ['Portage directeur non encore formalisé', 'Dépendance à un seul sponsor intermédiaire'],
    nextSteps: [
      'Planifier session test avec 3 analystes Compliance',
      'Valider les critères de déclenchement avec le Responsable',
      'Formaliser le portage directeur',
    ],
    notesMeta:
      'Deuxième projet le plus avancé. DPO validé. Budget confirmé. Point de vigilance : portage directeur non formalisé.',
    module: 'Module 3',
    typeIA: 'Machine Learning / Prédictif',
    prioriteBudget: 'Budget 2026 engagé',
    coach: COACH,
    lastUpdated: UPDATED,
    validated: false,
  },
  {
    notionPageId: 'mock-uc3',
    id: 'UC3',
    name: 'Scoring CV',
    status: 'PROTOTYPE',
    nextSession: '19/06/2026 — Point coaching',
    confidence: 'medium',
    avancement: 35,
    vp: 'Automatiser la présélection des candidats sur la base de critères objectifs définis par les RH, pour réduire le temps de traitement et limiter les biais.',
    conformite: {
      dpo: 'En cours',
      risk: 'Fort',
      perso: true,
      notes: [
        'Données personnelles candidats (CV, parcours)',
        'Validation DPO en cours — non finalisée',
        'Audit biais algorithmique obligatoire avant production',
        'Risque RGPD fort sans validation',
      ],
    },
    team: [
      { name: 'Porteur UC3', role: 'Chargé de Recrutement', org: 'BGL RH' },
      { name: 'Porteur 2 UC3', role: 'Data Analyst', org: 'BGL BNP' },
      { name: 'Porteur 3 UC3', role: 'RH Partenaire', org: 'BGL BNP' },
    ],
    stakeholders: [
      { name: 'DRH BGL', role: 'Sponsor', org: 'Direction RH' },
      { name: 'DPO BGL', role: 'Conformité', org: 'BGL BNP' },
      { name: 'Matthieu Chéreau', role: 'Coach', org: 'INSKIP' },
    ],
    specs: 3,
    gouv: 2,
    budget: 2,
    tests: 1,
    conformiteScore: 2,
    objectives: [
      { cat: 'MODÈLE SCORING RH', desc: 'Modèle de scoring sur critères objectifs DRH validés', pct: 60 },
      { cat: 'TEST CORPUS CV', desc: 'Test sur 50 CV réels avec contrôle humain', pct: 25 },
      { cat: 'AUDIT BIAIS + DPO', desc: 'Audit biais algorithmique et finalisation DPO', pct: 10 },
    ],
    achievements: [
      'Modèle de scoring basé sur critères RH opérationnel',
      'Test partiel sur corpus contrôlé effectué',
    ],
    utilisateurs: [
      'Chargés de Recrutement — 5 à 8 utilisateurs',
      'Direction RH — commanditaire et responsable éthique',
      'Candidats — impactés par la décision algorithmique',
    ],
    warnings: [
      'Audit biais non planifié — bloquant pour le DPO',
      'Validation DPO non finalisée — déploiement impossible sans elle',
    ],
    nextSteps: [
      "Planifier l'audit biais avec le DPO en priorité absolue",
      'Présenter les résultats au groupe BNP pour validation',
      'Confirmer le budget 2026 avec la DRH',
    ],
    notesMeta:
      "Risque conformité élevé. L'audit biais est le blocage critique — sans lui, pas de validation DPO ni de déploiement en production.",
    module: 'Module 3',
    typeIA: 'Machine Learning / Prédictif',
    prioriteBudget: 'Budget 2026 à confirmer',
    coach: COACH,
    lastUpdated: UPDATED,
    validated: false,
  },
  {
    notionPageId: 'mock-uc5',
    id: 'UC5',
    name: 'Client Insight AI',
    status: 'IDEATION',
    nextSession: '19/06/2026 — Point coaching',
    confidence: 'medium',
    avancement: 20,
    vp: 'Agréger les signaux clients issus de sources multiples pour produire une vue enrichie à destination des conseillers.',
    conformite: {
      dpo: 'Non initié',
      risk: 'Moyen',
      perso: true,
      notes: [
        'Sources externes non encore validées',
        'Agrégation multi-sources : risque RGPD à cartographier',
        'Démarche DPO à initier dès prochaine session',
        'Données profil financier clients (sensibles)',
      ],
    },
    team: [
      { name: 'Porteur UC5', role: 'Conseiller Banque Privée', org: 'BGL BNP' },
      { name: 'Porteur 2 UC5', role: 'Data Engineer', org: 'BGL BNP' },
      { name: 'Porteur 3 UC5', role: 'Analyste Client', org: 'BGL BNP' },
    ],
    stakeholders: [
      { name: 'Aucun sponsor', role: '—', org: '—' },
      { name: 'Matthieu Chéreau', role: 'Coach', org: 'INSKIP' },
    ],
    specs: 2,
    gouv: 0,
    budget: 2,
    tests: 0,
    conformiteScore: 1,
    objectives: [
      { cat: 'VALIDATION SOURCES', desc: 'Identifier et valider les sources disponibles dans le data hub BGL', pct: 30 },
      { cat: 'ARCHITECTURE', desc: "Concevoir l'architecture d'agrégation multi-sources", pct: 10 },
      { cat: 'MAQUETTE RESTITUTION', desc: 'Produire une maquette pour les conseillers', pct: 5 },
    ],
    achievements: ['Architecture sources identifiée en session', 'Data hub BGL validé comme source principale'],
    utilisateurs: [
      'Conseillers Banque Privée — 20 à 30 cibles',
      'Direction Banque Privée — commanditaire potentiel',
      'Équipe Data BGL — intégration',
    ],
    warnings: [
      'Aucun sponsor identifié — bloquant pour le budget',
      'Dépendance non résolue sur sources externes (Module 4)',
      'Zéro test utilisateur réalisé',
    ],
    nextSteps: [
      'Identifier un sponsor côté Banque Privée',
      'Clarifier le statut des sources externes',
      'Initier la démarche DPO',
    ],
    notesMeta:
      "Gouvernance entièrement à construire. Aucun sponsor — c'est le blocage prioritaire. DPO à initier dès que la gouvernance est stabilisée.",
    module: 'Module 4',
    typeIA: 'Analyse de données / Dashboarding',
    prioriteBudget: 'Budget 2026 à confirmer',
    coach: COACH,
    lastUpdated: UPDATED,
    validated: false,
  },
  {
    notionPageId: 'mock-uc6',
    id: 'UC6',
    name: 'Cartographie BGL',
    status: 'IDEATION',
    nextSession: '26/06/2026 — Point coaching',
    confidence: 'high',
    avancement: 10,
    vp: "Cartographie visuelle et navigable de l'architecture fonctionnelle BGL à partir des procédures internes, pour les équipes Transformation et Audit.",
    conformite: {
      dpo: 'Non initié',
      risk: 'Faible',
      perso: false,
      notes: [
        'Pas de données personnelles (procédures internes)',
        'Risque conformité faible à ce stade',
        'DPO à initier en phase prototype',
        'Hébergement interne BGL prévu',
      ],
    },
    team: [
      { name: 'Victor Dilion', role: 'Porteur principal', org: 'BGL BNP' },
      { name: 'Pierre-Etienne Staes', role: 'Développement graphe', org: 'BGL BNP' },
      { name: 'Sylvain Sarda', role: 'Référent Transformation', org: 'BGL BNP' },
    ],
    stakeholders: [
      { name: 'Équipe Data Lab', role: 'Partenaire technique', org: 'BGL BNP' },
      { name: 'Direction Transformation', role: 'Sponsor potentiel', org: 'BGL COO' },
      { name: 'Matthieu Chéreau', role: 'Coach', org: 'INSKIP' },
    ],
    specs: 2,
    gouv: 1,
    budget: 2,
    tests: 0,
    conformiteScore: 0,
    objectives: [
      { cat: 'ANCRAGE DATA LAB', desc: 'Point avec Data Lab sur le projet RAG procédures existant', pct: 20 },
      { cat: 'UTILISATEURS & MAQUETTE', desc: 'Qualifier les utilisateurs et produire une maquette basse fidélité', pct: 10 },
      { cat: 'PROTOTYPE GRAPHE', desc: 'Prototype de cartographie sur un sous-ensemble de procédures', pct: 0 },
    ],
    achievements: ['Portage sur projet Data Lab existant (RAG procédures)', 'Statut Ready selon évaluation Module 4'],
    utilisateurs: [
      'Équipes Transformation / COO — navigabilité procédures',
      'Équipes Audit interne — cartographie dépendances',
      'Management opérationnel — vue fonctionnelle',
    ],
    warnings: [
      'Aucun point Data Lab fait spécifiquement pour ce projet',
      'Pas de prototype — critère : navigabilité du graphe, pas précision LLM',
      'Budget propre à confirmer',
    ],
    nextSteps: [
      "Organiser un point avec l'équipe Data Lab",
      'Définir les utilisateurs cibles et critère de succès',
      'Construire le premier prototype de graphe',
    ],
    notesMeta:
      'Adossé à un projet Data Lab existant (RAG procédures). Force : base technique disponible. Faiblesse : aucun point Data Lab spécifique, aucun prototype.',
    module: 'Module 4',
    typeIA: 'IA générative (LLM / RAG)',
    prioriteBudget: 'Budget 2026 à confirmer',
    coach: COACH,
    lastUpdated: UPDATED,
    validated: false,
  },
  {
    notionPageId: 'mock-uc4',
    id: 'UC4',
    name: 'Best Offer crédit',
    status: 'IDEATION',
    nextSession: '26/06/2026 — Point coaching',
    confidence: 'low',
    avancement: 15,
    vp: 'Recommander automatiquement la meilleure offre de crédit hypothécaire personnalisée à partir du profil de risque client et des conditions de marché.',
    conformite: {
      dpo: 'Non initié',
      risk: 'Fort',
      perso: true,
      notes: [
        'Données financières et scoring crédit (très sensibles)',
        'Décision à impact financier direct — risque RGPD fort',
        "DPO à initier dès stabilisation du cas d'usage",
        'Risque réglementaire bancaire (CCD2, MiFID2)',
      ],
    },
    team: [
      { name: 'Porteur UC4', role: 'Chargé de clientèle', org: 'BGL BNP' },
      { name: 'Porteur 2 UC4', role: 'Data Analyst', org: 'BGL BNP' },
      { name: 'Porteur 3 UC4', role: 'Analyste Crédit', org: 'BGL BNP' },
    ],
    stakeholders: [
      { name: 'Aucun sponsor', role: '—', org: '—' },
      { name: 'Matthieu Chéreau', role: 'Coach', org: 'INSKIP' },
    ],
    specs: 1,
    gouv: 0,
    budget: 2,
    tests: 0,
    conformiteScore: 0,
    objectives: [
      { cat: "CADRAGE CAS D'USAGE", desc: "Formaliser et stabiliser le cas d'usage crédit hypothécaire", pct: 20 },
      { cat: 'ACCÈS DONNÉES SCORING', desc: "Clarifier l'accès aux données de scoring crédit BGL", pct: 10 },
      { cat: 'PROTOTYPE RECOMMANDATION', desc: "Premier prototype de recommandation d'offre", pct: 0 },
    ],
    achievements: ["Cas d'usage en cours de cadrage — première version identifiée"],
    utilisateurs: [
      'Chargés de clientèle Particuliers — 15 à 20 cibles',
      'Direction Crédits — commanditaire potentiel',
      'Clients particuliers — bénéficiaires finaux',
    ],
    warnings: [
      'Haute complexité — accès données scoring crédit non résolu',
      'Aucun sponsor — sans portage, pas de données ni de budget',
      'Conformité non initiée — risque réglementaire élevé',
      'Confidence faible — à revoir en priorité',
    ],
    nextSteps: [
      'Identifier un sponsor côté Direction Crédits',
      "Stabiliser le PRD avant d'approcher la DSI",
      'Démarche préliminaire DPO sur le périmètre',
    ],
    notesMeta:
      'Fort potentiel métier mais complexité maximale. À prioriser en Phase 2 après stabilisation des projets moins complexes. Confidence faible justifiée.',
    module: 'Module 4',
    typeIA: 'Machine Learning / Prédictif',
    prioriteBudget: 'Budget 2027 envisagé',
    coach: COACH,
    lastUpdated: UPDATED,
    validated: false,
  },
  {
    notionPageId: 'mock-uc2',
    id: 'UC2',
    name: 'Profilage multicanal',
    status: 'IDEATION',
    nextSession: 'TBD — Blocage DPO actif',
    confidence: 'medium',
    avancement: 5,
    vp: 'Analyser et router les interactions clients (emails, canaux digitaux, téléphone) pour construire un profil comportemental par segment.',
    conformite: {
      dpo: 'BLOQUANT',
      risk: 'Fort',
      perso: true,
      notes: [
        'Accès emails externes clients BLOQUÉ par le DPO',
        'Enjeu juridique critique — condition à tout avancement',
        'Données comportementales sensibles (profilage client)',
        'Sans feu vert DPO, aucune source principale disponible',
      ],
    },
    team: [
      { name: 'Olivier Péné', role: 'Porteur principal', org: 'BGL BNP' },
      { name: 'Christophe Leroy', role: 'Développement', org: 'BGL BNP' },
      { name: 'David Zimnoch', role: 'Référent canal digital', org: 'BGL BNP' },
    ],
    stakeholders: [
      { name: 'Tribe Digital Channel', role: 'Partenaire technique', org: 'BGL BNP' },
      { name: 'DPO BGL', role: 'Blocage actif', org: 'BGL BNP' },
      { name: 'Matthieu Chéreau', role: 'Coach', org: 'INSKIP' },
    ],
    specs: 1,
    gouv: 0,
    budget: 1,
    tests: 0,
    conformiteScore: 0,
    objectives: [
      { cat: 'DÉBLOCAGE DPO', desc: "Résoudre le blocage juridique DPO sur l'accès aux emails externes", pct: 5 },
      { cat: 'MODÈLE SEGMENTATION', desc: 'Construire les premiers clusters comportementaux via data hub', pct: 0 },
      { cat: 'CADRAGE BUDGET 2027', desc: 'Formaliser le PRD et inscrire dans la roadmap 2027', pct: 10 },
    ],
    achievements: ['Architecture sources identifiée', 'Data hub validé pour canaux digitaux et téléphone'],
    utilisateurs: [
      'Équipes Relation Client / Canal Digital — 10 à 15 cibles',
      'CDO / Tribe Digital Channel — commanditaire',
      'Direction Marketing — bénéficiaire des insights',
    ],
    warnings: [
      'Accès emails externes bloqué par le DPO — condition critique absolue',
      'Budget 2027 uniquement — aucun budget 2026 identifié',
      'Aucun sponsor identifié — projet en attente de portage',
    ],
    nextSteps: [
      'Résoudre le blocage DPO avant tout autre avancement',
      'Point Data Lab sur les sources disponibles dans le data hub',
      'Formaliser le PRD pour la roadmap 2027',
    ],
    notesMeta:
      "Blocage DPO critique. Matthieu a indiqué qu'il adaptera l'accompagnement selon l'issue du point DPO. Budget 2027 uniquement envisagé.",
    module: 'Module 4',
    typeIA: 'Automatisation de processus',
    prioriteBudget: 'Budget 2027 envisagé',
    coach: COACH,
    lastUpdated: UPDATED,
    validated: false,
  },
]
