import type { CommunityEvent, Question, UseCase } from '@/types/community'

// Données de démonstration (mock-first). Persistées et modifiables côté client
// via DataProvider. Remplaçables par un vrai backend ultérieurement.

export const SEED_USE_CASES: UseCase[] = [
  {
    id: 'uc-001',
    title: 'Assistant de réponse aux emails clients',
    description:
      "Pré-rédiger les réponses aux emails entrants des clients à partir du contexte CRM, avec validation humaine avant envoi.",
    businessUnit: 'Banque de détail',
    domaine: 'Relation client',
    votes: 47,
    submittedBy: 'Yu-Ying Chap',
    createdAt: '2026-05-04',
    priorite: 'Prioritaire',
    nature: 'Quick Win Copilot',
  },
  {
    id: 'uc-002',
    title: 'Comptes-rendus automatiques de réunion',
    description:
      'Générer un compte-rendu structuré (décisions, actions, responsables) à partir de la transcription des réunions internes.',
    businessUnit: 'Opérations',
    domaine: 'Productivité interne',
    votes: 41,
    submittedBy: 'Patrick Marlier',
    createdAt: '2026-05-06',
    priorite: 'Prioritaire',
    nature: 'Quick Win Copilot',
  },
  {
    id: 'uc-003',
    title: 'Synthèse des circulaires CSSF',
    description:
      'Résumer et qualifier les nouvelles circulaires CSSF et textes réglementaires, avec extraction des obligations applicables à BGL.',
    businessUnit: 'Risk & Compliance',
    domaine: 'Juridique & Réglementaire',
    votes: 38,
    submittedBy: 'David Zimnoch',
    createdAt: '2026-05-09',
    priorite: 'Prioritaire',
    nature: 'Solution custom',
  },
  {
    id: 'uc-004',
    title: 'Aide à la rédaction des mémos crédit',
    description:
      "Structurer et pré-rédiger les mémos de crédit à partir du dossier client et des données de scoring, l'analyste validant et signant.",
    businessUnit: 'Banque Privée / Wealth',
    domaine: 'Crédit & Financement',
    votes: 33,
    submittedBy: 'Samir Haddad',
    createdAt: '2026-05-12',
    nature: 'Solution custom',
  },
  {
    id: 'uc-005',
    title: 'Qualification des alertes AML',
    description:
      "Aider les analystes à prioriser et documenter les alertes de transactions suspectes, en réduisant les faux positifs.",
    businessUnit: 'Risk & Compliance',
    domaine: 'Conformité & AML',
    votes: 29,
    submittedBy: 'Najla Ben Salem',
    createdAt: '2026-05-15',
    priorite: 'Prioritaire',
  },
  {
    id: 'uc-006',
    title: 'Contrôle documentaire KYC à l’onboarding',
    description:
      "Vérifier la complétude et la cohérence des pièces KYC lors de l'entrée en relation, et signaler les pièces manquantes.",
    businessUnit: 'Opérations',
    domaine: 'Conformité & AML',
    votes: 24,
    submittedBy: 'Camille Lefèvre',
    createdAt: '2026-05-18',
  },
  {
    id: 'uc-007',
    title: 'Assistant de recherche fonds & marchés',
    description:
      'Agréger et synthétiser les notes de recherche, factsheets de fonds et données de marché pour les conseillers Wealth.',
    businessUnit: 'Banque Privée / Wealth',
    domaine: 'Reporting & Data',
    votes: 21,
    submittedBy: 'Laurent Weber',
    createdAt: '2026-05-21',
    nature: 'Quick Win Mistral',
  },
  {
    id: 'uc-008',
    title: 'Tri et priorisation des tickets IT',
    description:
      'Classer automatiquement les tickets du support IT par catégorie et urgence, et suggérer une première réponse.',
    businessUnit: 'IT / Data',
    domaine: 'Back-office & Opérations',
    votes: 17,
    submittedBy: 'Maxime Thill',
    createdAt: '2026-05-24',
    nature: 'Quick Win Copilot',
  },
  {
    id: 'uc-009',
    title: 'Génération de fiches de poste & présélection CV',
    description:
      'Rédiger des fiches de poste à partir d’un brief et présélectionner les CV sur critères objectifs (avec contrôle humain et audit de biais).',
    businessUnit: 'Ressources Humaines',
    domaine: 'Recrutement & RH',
    votes: 14,
    submittedBy: 'Odile Faber',
    createdAt: '2026-05-27',
  },
  {
    id: 'uc-010',
    title: 'Chatbot RH interne (politiques & congés)',
    description:
      'Répondre aux questions des collaborateurs sur les politiques RH, congés et avantages à partir des documents internes.',
    businessUnit: 'Ressources Humaines',
    domaine: 'Productivité interne',
    votes: 11,
    submittedBy: 'Douceline Mendy',
    createdAt: '2026-05-30',
    nature: 'Quick Win Copilot',
  },
  {
    id: 'uc-011',
    title: 'Personnalisation des campagnes marketing',
    description:
      'Adapter les messages et segments des campagnes à partir des signaux clients, dans le respect du consentement et du RGPD.',
    businessUnit: 'Marketing & Communication',
    domaine: 'Marketing & Acquisition',
    votes: 8,
    submittedBy: 'Kevin Schmit',
    createdAt: '2026-06-02',
  },
  {
    id: 'uc-012',
    title: 'Résumé des appels du centre de relation',
    description:
      "Produire un résumé et une qualification des appels entrants pour alimenter le CRM et le suivi de la relation.",
    businessUnit: 'Banque de détail',
    domaine: 'Relation client',
    votes: 5,
    submittedBy: 'Thomas Wagner',
    createdAt: '2026-06-05',
  },
]

export const SEED_EVENTS: CommunityEvent[] = [
  {
    id: 'ev-001',
    title: 'Café IA #4 — Partage de cas d’usage',
    format: 'Café IA',
    date: '2026-06-18',
    time: '12:30',
    location: 'Luxembourg — Atrium, RDC',
    description: 'Échange informel autour des cas d’usage en cours, retours d’expérience et questions ouvertes.',
    organizer: 'Victor Dilion',
  },
  {
    id: 'ev-002',
    title: 'Lunch & Learn — Le RAG en pratique',
    format: 'Lunch & Learn',
    date: '2026-06-25',
    time: '12:00',
    location: 'Luxembourg — Salle Moselle',
    description: 'Atelier déjeuner : comprendre le Retrieval-Augmented Generation et quand l’utiliser sur vos projets.',
    organizer: 'Pierre-Etienne Staes',
  },
  {
    id: 'ev-003',
    title: 'Démo trimestrielle Q2 2026',
    format: 'Démo trimestrielle',
    date: '2026-06-30',
    time: '16:00',
    location: 'Luxembourg — Auditorium',
    description: 'Présentation des avancées des 7 projets IA du programme devant le comité et les équipes invitées.',
    organizer: 'Matthieu Chéreau',
  },
  {
    id: 'ev-004',
    title: 'Polytechnique — Mise à jour LLM & agents',
    format: 'Polytechnique Executive Education',
    date: '2026-07-03',
    time: '09:00',
    location: 'Distanciel',
    description: 'Formation de mise à jour sur les dernières évolutions des modèles, des agents et de leurs usages bancaires.',
    organizer: 'Polytechnique Executive Education',
  },
  {
    id: 'ev-005',
    title: 'Café IA #5 — Conformité & AI Act',
    format: 'Café IA',
    date: '2026-07-16',
    time: '12:30',
    location: 'Luxembourg — Atrium, RDC',
    description: 'Focus sur la qualification AI Act des cas d’usage et les bons réflexes de conformité.',
    organizer: 'Sylvain Sarda',
  },
  {
    id: 'ev-006',
    title: 'Lunch & Learn — Prompting avancé',
    format: 'Lunch & Learn',
    date: '2026-09-10',
    time: '12:00',
    location: 'Luxembourg — Salle Sûre',
    description: 'Techniques de prompting structuré (rôle, contexte, instruction, contrainte) appliquées aux cas BGL.',
    organizer: 'Christophe Leroy',
  },
  {
    id: 'ev-007',
    title: 'Polytechnique — Posture du facilitateur',
    format: 'Polytechnique Executive Education',
    date: '2026-09-24',
    time: '09:00',
    location: 'Distanciel',
    description: 'Volet posture : faire évoluer les facilitateurs dans leur rôle d’ambassadeur et de coach IA.',
    organizer: 'Polytechnique Executive Education',
  },
  {
    id: 'ev-008',
    title: 'Démo trimestrielle Q3 2026',
    format: 'Démo trimestrielle',
    date: '2026-09-29',
    time: '16:00',
    location: 'Luxembourg — Auditorium',
    description: 'Bilan d’étape du trimestre : pilotes lancés, premiers KPI et prochaines étapes.',
    organizer: 'Matthieu Chéreau',
  },
]

export const SEED_QUESTIONS: Question[] = [
  {
    id: 'q-001',
    text: 'Peut-on utiliser Copilot sur des données clients sans validation DPO préalable ?',
    askedBy: 'Anonyme',
    createdAt: '2026-06-08',
    answer:
      'Non. Toute donnée client (PII) nécessite une base légale et le passage par une instance dédiée (Azure OpenAI EU / Mistral). Sollicitez le DPO via l’annuaire conformité.',
  },
  {
    id: 'q-002',
    text: 'Comment proposer un cas d’usage si je ne suis pas facilitateur ?',
    askedBy: 'Anonyme',
    createdAt: '2026-06-10',
  },
]
